"""Bootstrap prompt templates."""

BOOTSTRAP_PROMPT = (
    "Create a directory called builder. cd into it. Initialize a git repo. "
    "Create an appropriate .gitignore for the project. "
    "Create a brief README.md (~15 lines) — what the project is, how to build and "
    "run it, and how to develop. Do not describe features in detail — REQUIREMENTS.md "
    "and SPEC.md cover that. The project description: {description}. "
    "A file called REQUIREMENTS.md already exists in this directory — it contains "
    "the original project requirements exactly as provided by the user. Do NOT modify "
    "or overwrite REQUIREMENTS.md. Use it as the primary input when writing SPEC.md. "
    "Create a SPEC.md that captures TECHNICAL DECISIONS only (~40-60 lines). "
    "SPEC.md should include: "
    "(1) a high-level summary of what the project is, "
    "(2) the tech stack and language choices, "
    "(3) the architecture approach — layers, dependency rules, project structure, "
    "(4) cross-cutting concerns — authentication strategy, multi-tenancy approach, "
    "error handling conventions, "
    "(5) acceptance criteria — what 'done' looks like, described at the feature level "
    "(e.g. 'members can be managed', 'attendance can be tracked') not the field level. "
    "Do NOT include entity field definitions, API route tables, page layouts, or DTO "
    "shapes in SPEC.md — those details will be planned progressively as features are "
    "built. REQUIREMENTS.md is the authoritative source for feature details — SPEC.md "
    "captures the technical decisions for how to build them. "
    "Do NOT create a TASKS.md — task planning happens later. "
    "Commit with message '[bootstrap] Initial commit: project spec'. "
    "Run 'gh repo create {gh_user}/{name} --public --source .' and push."
)

