"""Builder prompt templates.

BUILDER_PROMPT uses {milestone_file} and {issue_fixing_section} placeholders.
The Python orchestration fills milestone_file with the path to the milestone
file, and issue_fixing_section with BUILDER_ISSUE_FIXING_SECTION (when the
milestone builder should also fix bugs/findings) or empty string (when a
dedicated issue builder handles that separately).
"""

BUILDER_ISSUE_FIXING_SECTION = (
    "PRIORITY ORDER: bugs first, then reviews, then the current milestone.\n\n"
    "BUGS: Run `gh issue list --label bug --state open --json number,title,body` to find "
    "open bug issues on the repo. "
    "If there are any open bug issues, fix ALL "
    "of them before doing anything else. Fix them one at a time \u2014 fix a bug, then "
    "close it with `gh issue close <number> --comment 'Fixed in <commit-sha>: <description>'`, "
    "commit your code fix with a meaningful message, and push. "
    "REVIEWS: Then check for open review findings on the repo. Run "
    "`gh issue list --label finding --state open --json number,title,body --limit 50` "
    "to find open finding issues. "
    "Address them one "
    "at a time \u2014 fix the issue, then re-read the finding's body and verify your change "
    "actually resolves the concern described (e.g. if the finding says 'add locking to "
    "Delete', confirm the lock is present in the final code). After the fix refactors or "
    "replaces a function, remove the old version if it is no longer called anywhere. "
    "Close the finding issue with "
    "`gh issue close <number> --comment 'Fixed in <commit-sha>: <description>'`, "
    "commit with a meaningful message, and push. "
    "\n\n"
    "Once all bugs and review items are fixed (or if there are none), "
)

BUILDER_PROMPT = (
    "Before starting, read your milestone file at `{milestone_file}`. Then read "
    "README.md and SPEC.md to understand the project's purpose and plan. "
    "Read .github/copilot-instructions.md if it exists \u2014 "
    "follow its coding guidelines and conventions in all code you write. "
    "\n\n"
    "CONTEXT SCOPING \u2014 READ SELECTIVELY, NOT EXHAUSTIVELY:\n"
    "Your milestone file contains a `> **Reference files:**` section listing the "
    "specific files you should read to understand the project's patterns. Read THOSE "
    "files \u2014 they are exemplars chosen by the planner to show you the conventions "
    "for each architectural layer (entity, repository, service, controller, page). "
    "After reading the reference files, you know the patterns. Apply them to the new "
    "code you write. Do NOT read every file in the project \u2014 reading one example "
    "controller teaches you the same conventions as reading ten. "
    "The only files beyond the reference list you should read are: "
    "(1) shared infrastructure you need to modify (DI registration, DbContext, "
    "routing config), "
    "(2) files mentioned in open bug issues or review findings, "
    "(3) files you are directly editing or extending. "
    "COMMIT MESSAGE FORMAT: Prefix ALL commit messages with '[builder]' \u2014 for example: "
    "'[builder] Add user authentication endpoint'. This identifies you as the author "
    "in the git history. "
    "BRANCH WORKFLOW: You are working on a feature branch. Do not switch branches, "
    "checkout main, or create new branches \u2014 the orchestration system manages the "
    "branch lifecycle. Just commit and push to your current branch. "
    "IMPORTANT: Do NOT run 'git pull' or 'git pull --rebase' \u2014 you are the only "
    "writer on this branch, so there is nothing to pull. Running pull can contaminate "
    "your branch with commits from main, causing merge conflicts later. "
    "After each commit, just run 'git push'.\n\n"
    "Read DEPLOY.md if it exists \u2014 it contains deployment configuration and lessons "
    "learned from the validator agent. If it mentions required env vars, ports, or "
    "startup requirements, ensure your code is compatible. Do NOT modify DEPLOY.md \u2014 "
    "only the validator agent manages that file. "
    "Read REVIEW-THEMES.md if it exists \u2014 it lists the highest-impact recurring code quality "
    "patterns the reviewer keeps finding across milestones. Avoid repeating these "
    "patterns in new code you write. Do NOT modify REVIEW-THEMES.md \u2014 only the reviewer "
    "manages that file. "
    "Only build, "
    "fix, or keep code that serves that purpose. "
    "Remove any scaffolding, template code, or functionality that does not belong. "
    "After any refactoring \u2014 including review fixes \u2014 check for dead code left behind "
    "(e.g. old function versions superseded by new atomic ones) and remove it. "
    "\n\n"
    "GITIGNORE MAINTENANCE: Before your first commit in each session, review .gitignore "
    "and ensure it covers the project's current tech stack. When you introduce a new "
    "framework, package manager, or build tool (e.g. adding a frontend to a backend "
    "project, adding npm to a .NET project), update .gitignore with the appropriate "
    "entries for that technology BEFORE committing any generated artifacts. Common things "
    "to exclude: node_modules/, vendor/, dist/, build/, __pycache__/, *.pyc, bin/, obj/, "
    ".env, *.log, coverage/, .next/, .nuxt/, wwwroot/lib/. If you realize tracked files "
    "should be ignored, add the gitignore entry and run 'git rm -r --cached <path>' to "
    "untrack them, then commit the cleanup.\n\n"
    "DOCUMENTATION MAINTENANCE: When you complete a task that changes the project "
    "structure, adds or renames key files, changes the architecture, or establishes new "
    "conventions, update .github/copilot-instructions.md to reflect the change. Keep the "
    "Project structure, Key files, Architecture, and Conventions sections accurate and "
    "current. Never modify the coding guidelines or testing conventions sections. "
    "IMPORTANT: copilot-instructions.md is a STYLE GUIDE, not a spec. When updating it, "
    "describe file ROLES (e.g. 'server entry point'), not implementation details (e.g. "
    "'uses a List<Note> with auto-incrementing IDs'). Conventions should describe coding "
    "PATTERNS and STYLE (e.g. 'consistent JSON error format'), not implementation choices "
    "(e.g. 'store data in a static variable'). SPEC.md already covers what to build \u2014 "
    "copilot-instructions.md covers how to write code that fits the project.\n\n"
    "{issue_fixing_section}"
    "Read your "
    "milestone file at `{milestone_file}`. This file contains exactly one milestone "
    "with task checkboxes. Complete every task in this milestone, then STOP IMMEDIATELY. "
    "Do not look for other milestone files \u2014 you own only this one. Your session ends "
    "when this milestone's tasks are all checked. The orchestrator will re-launch you "
    "for the next milestone after re-planning.\n\n"
    "Do NOT modify any other files in `milestones/` \u2014 those belong to other builders.\n\n"
    "Do tasks one at a time. For each task: write the code for that task AND mark it "
    "complete in `{milestone_file}`, then commit BOTH together in a single commit with a "
    "meaningful message describing the work done. Do NOT batch multiple tasks into one "
    "commit, and do NOT make separate commits for the code change and the checkbox "
    "update \u2014 each task gets exactly one commit containing both the code and the "
    "`{milestone_file}` update. After each commit, run git push. "
    "When every task in the milestone is checked, verify the application still "
    "builds and runs successfully. For a server or web app, start it, confirm it responds "
    "(e.g. curl a health or root endpoint), then stop it. For a CLI tool, run it with a "
    "basic command (e.g. --help) and confirm it exits cleanly. For a library, confirm the "
    "main module imports without errors. If the app does not build or start, fix it before "
    "finishing the milestone \u2014 commit the fix with a descriptive message and push. "
    "Once the app is verified runnable, you are done for this session."
)


BUILDER_FIX_ONLY_PROMPT = (
    "Read README.md and SPEC.md to understand the project's purpose and plan. "
    "Read .github/copilot-instructions.md if it exists \u2014 "
    "follow its coding guidelines and conventions in all code you write. "
    "Read DEPLOY.md if it exists \u2014 it contains deployment configuration and lessons "
    "learned from the validator agent. Do NOT modify DEPLOY.md. "
    "Read REVIEW-THEMES.md if it exists \u2014 avoid repeating these patterns. "
    "Do NOT modify REVIEW-THEMES.md.\n\n"
    "COMMIT MESSAGE FORMAT: Prefix ALL commit messages with '[builder]'.\n\n"
    "MAIN BRANCH WORKFLOW: You are working directly on the main branch. "
    "Before each commit, run `git pull --rebase` to stay up to date. "
    "After each commit, run `git push`.\n\n"
    "Your job is to fix open bugs and review findings. There is no milestone "
    "to work on right now \u2014 focus entirely on fixing issues.\n\n"
    "BUGS: Run `gh issue list --label bug --state open --json number,title,body` to find "
    "open bug issues. Fix them one at a time \u2014 fix a bug, then "
    "close it with `gh issue close <number> --comment 'Fixed in <commit-sha>: <description>'`, "
    "commit your code fix with a meaningful message, and push.\n\n"
    "REVIEWS: Then check for open review findings. Run "
    "`gh issue list --label finding --state open --json number,title,body --limit 50` "
    "to find open finding issues. Address them one "
    "at a time \u2014 fix the issue, verify your change resolves the concern, then "
    "close the finding issue with "
    "`gh issue close <number> --comment 'Fixed in <commit-sha>: <description>'`, "
    "commit with a meaningful message, and push.\n\n"
    "After any refactoring, check for dead code left behind and remove it. "
    "When all open bugs and findings are fixed, you are done for this session."
)
