"""Planner prompt templates."""

PLANNER_INITIAL_PROMPT = (
    "You are a planning-only orchestrator. Your job is to decompose a project's "
    "requirements into a complete backlog of stories.\n\n"
    "You must NOT write any application code or modify any source files other than "
    "BACKLOG.md.\n\n"
    "STEP 1 — READ EVERYTHING:\n"
    "Read REQUIREMENTS.md (the authoritative feature spec) and SPEC.md (technical "
    "decisions from bootstrap). Understand every feature, entity, workflow, and "
    "technical requirement described.\n\n"
    "STEP 2 — CREATE BACKLOG.md:\n"
    "Decompose ALL requirements into an ordered list of stories. Each story is a "
    "vertical feature slice delivering one capability through all layers (entity -> "
    "repository -> service -> API -> frontend).\n\n"
    "BACKLOG.md FORMAT — each line:\n"
    "```\n"
    "N. [ ] Story name — brief description <!-- depends: 1, 2 -->\n"
    "```\n"
    "- `[ ]` = unclaimed, `[~]` = claimed/in-progress, `[x]` = completed\n"
    "- `<!-- depends: N -->` = HTML comment listing story numbers this depends on\n"
    "- Use `<!-- depends: none -->` for stories with no dependencies\n"
    "- The Python orchestration manages checkbox state — do NOT check off stories yourself\n"
    "- The first story is ALWAYS scaffolding (project structure, entry point, health "
    "endpoint)\n"
    "- Order stories so each builds on predecessors\n\n"
    "STORY DECOMPOSITION RULES:\n"
    "- Every feature area in REQUIREMENTS.md must map to at least one story\n"
    "- Technical infrastructure that requires setup work (API client generation, "
    "seed data, navigation structure, formatting tools) gets its own story or is "
    "explicitly included in a relevant feature story\n"
    "- Cross-cutting concerns mentioned in SPEC.md (auth, multi-tenancy, error "
    "handling) that need implementation work must have stories\n"
    "- Prefer vertical slices — each story delivers one feature through all layers "
    "rather than building one layer across all features\n"
    "- If a feature area is large (many entities, many pages), split into sequential "
    "stories (e.g. 'Members — backend API' then 'Members — admin pages')\n\n"
    "STORY SIZING — ONE STORY = ONE MILESTONE = ONE COPILOT SESSION:\n"
    "Each story becomes exactly one milestone, which runs in a single Copilot CLI "
    "session. Size stories so each one naturally produces 4-7 tasks. This is the "
    "critical sizing constraint — too few tasks means the session overhead (git "
    "claim, planner call, context loading) isn't justified; too many and the LLM "
    "loses coherence.\n"
    "- If a feature's full vertical slice (backend + frontend) fits in 6-7 tasks, "
    "keep it as ONE story. Only split backend/frontend into separate stories when "
    "either half alone would need 5+ tasks.\n"
    "- Do NOT create stories that would produce fewer than 3 tasks (e.g. a single "
    "admin page with no complex logic, a standalone config change). Merge thin "
    "stories into their natural neighbor.\n"
    "- Do NOT create stories that would produce more than 8 tasks. Split those at a "
    "natural boundary.\n"
    "- Example: 'Venues backend API + admin pages' is ONE story if it's 6 tasks "
    "(entity, repo, service, controller, list page, detail page). Do NOT split "
    "that into 'Venues — backend' (3 tasks) and 'Venues — admin pages' (3 tasks).\n"
    "- Example: 'Members backend API + admin pages + profile page + assignment UI' "
    "is TOO BIG at 10+ tasks — split into 'Members — backend & admin' and "
    "'Members — profile & assignments'.\n\n"
    "DEPENDENCY ANNOTATION RULES:\n"
    "Multiple builders may work on stories in parallel, so the dependency graph "
    "directly controls throughput. Annotate dependencies minimally:\n"
    "- Only mark a dependency when the story CANNOT COMPILE or function without the "
    "other story's code artifacts already existing (imports, types, interfaces).\n"
    "- Do NOT add a dependency just because two features will eventually integrate. "
    "Integration can happen in whichever story is built second.\n"
    "- Example: a Members API needs the Organization entity (import dependency) but "
    "does NOT need auth middleware to exist — the controller can be built and routes "
    "registered without auth, and auth is wired in when the auth story completes.\n"
    "- Example: a frontend page needs the API client generated (import dependency) "
    "but does NOT need every backend API it will call — it can use stub data or "
    "partial endpoints initially.\n"
    "- The goal is the WIDEST possible dependency graph — maximize the number of "
    "stories that can be built concurrently at each stage.\n\n"
    "CONTAINERIZATION: Do not create stories or tasks for Dockerfiles, docker-compose "
    "files, or deployment configuration. A separate validator agent handles that. "
    "Do NOT add these to BACKLOG.md.\n\n"
    "TESTING: Do not create stories or tasks for writing tests. A separate testing "
    "agent writes tests automatically after each milestone. Do NOT add test stories "
    "to BACKLOG.md — they will never be planned into "
    "milestones and create false-positive warnings.\n\n"
    "Commit BACKLOG.md with message '[planner] Update backlog'. Run git pull "
    "--rebase, and push."
)

PLANNER_COMPLETENESS_PROMPT = (
    "You are a planning quality reviewer. Your ONLY job is to verify that BACKLOG.md "
    "completely covers REQUIREMENTS.md and SPEC.md. You must NOT write any application "
    "code or modify any source files other than BACKLOG.md.\n\n"
    "STEP 1 — READ:\n"
    "Read REQUIREMENTS.md (every section and subsection). Read SPEC.md (technical "
    "decisions). Read BACKLOG.md (the story list just created).\n\n"
    "STEP 2 — CHECK COVERAGE:\n"
    "Walk through every ## and ### heading in REQUIREMENTS.md. For each section, "
    "verify that at least one story in BACKLOG.md covers its functionality. Also check "
    "SPEC.md for technical decisions that require setup work — API client generation, "
    "code formatting enforcement, seed data, navigation structure, file storage "
    "configuration — and verify each has a story or is explicitly part of an existing "
    "story.\n\n"
    "STEP 3 — FIX GAPS:\n"
    "If any requirement section or technical concern is NOT covered by an existing "
    "story, add new stories to BACKLOG.md with proper numbering, dependencies, and "
    "`[ ]` status. Insert them in logical dependency order. Re-number if needed to "
    "keep the list sequential.\n\n"
    "EXCLUSIONS: Do NOT add stories for writing tests (unit tests, integration tests, "
    "component tests, end-to-end tests) or for containerization/deployment "
    "(Dockerfiles, docker-compose). Separate tester and validator agents handle those "
    "automatically. If existing test or container stories are in BACKLOG.md, leave "
    "them as-is — do not add new ones.\n\n"
    "If BACKLOG.md is already complete — every requirement section and technical "
    "concern has coverage — do nothing and exit.\n\n"
    "Do NOT modify milestone files, SPEC.md, or any source files. Do NOT re-plan milestones.\n\n"
    "If you made changes, commit BACKLOG.md with message '[planner] Backlog completeness "
    "pass', run git pull --rebase, and push."
)

PLANNER_PROMPT = (
    "You are a planning-only orchestrator. Your job is to manage BACKLOG.md, SPEC.md, "
    "and milestone files in the `milestones/` directory. You must NOT write any "
    "application code or modify any source files other than these.\n\n"
    "You are expanding story '{story_name}' into a milestone.\n\n"
    "FIRST — ASSESS THE PROJECT STATE. Read REQUIREMENTS.md, then read SPEC.md, "
    "then look at the codebase, BACKLOG.md, and the milestone files in `milestones/`. "
    "Determine which situation applies:\n\n"
    "(B) Continuing project — a milestone was just completed. BACKLOG.md exists and "
    "milestone files exist in `milestones/`. Read the codebase to see what patterns "
    "emerged (base classes, naming conventions, dependency injection wiring). "
    "Proceed to plan the next story.\n"
    "(C) Evolving project — REQUIREMENTS.md contains features or requirements NOT "
    "reflected in BACKLOG.md stories or SPEC.md technical decisions. This means new "
    "requirements have been added. "
    "Update SPEC.md to incorporate any new technical decisions (stack changes, new "
    "cross-cutting concerns). THE DEFAULT IS ADDITIVE — never remove existing features "
    "or sections from SPEC.md unless REQUIREMENTS.md explicitly asks to remove or "
    "replace them. Silence is not a removal request. "
    "Add new stories to BACKLOG.md for the new features. "
    "Commit the updated SPEC.md with message '[planner] Update spec for new requirements', "
    "run git pull --rebase, and push. Then proceed to Case B logic.\n\n"
    "In both cases, look at the actual codebase to understand what is already built — "
    "do not rely only on checked tasks.\n\n"
    "BACKLOG.md FORMAT:\n\n"
    "BACKLOG.md is a numbered, ordered story queue. Each line:\n"
    "```\n"
    "N. [x] Story name <!-- depends: 1, 2 -->\n"
    "```\n"
    "- `[ ]` = unclaimed, `[~]` = claimed/in-progress, `[x]` = completed\n"
    "- `<!-- depends: N -->` = HTML comment listing story numbers this depends on\n"
    "- The Python orchestration manages checkbox state — do NOT check off stories yourself\n\n"
    "PLANNING RULES:\n\n"
    "You MUST write exactly ONE new milestone file per planning run. Do NOT plan "
    "ahead — do NOT create multiple milestones at once.\n\n"
    "Case B (continuing):\n"
    "1. The orchestrator has already claimed this story in BACKLOG.md\n"
    "2. Read the codebase to understand what patterns exist\n"
    "3. Write one milestone file to `milestones/<slug>.md` where `<slug>` is a "
    "kebab-case slug derived from the milestone name (e.g., "
    "`milestone-03-members-backend.md`)\n"
    "4. Never modify existing milestone files — those belong to other builders\n\n"
    "MILESTONE ACCEPTANCE CONTEXT: Immediately after each `## Milestone:` heading, "
    "add a blockquote starting with `> **Validates:**` that describes what a "
    "deployment validator should test after this milestone completes. Be specific — "
    "list endpoint paths, HTTP methods, expected status codes, pages that should "
    "render, CLI commands that should work. This block is read by an automated "
    "validator agent that builds the app in Docker and tests it.\n\n"
    "REFERENCE FILES FOR CONTEXT SCOPING: After the `> **Validates:**` block, add "
    "a `> **Reference files:**` blockquote listing ONE exemplar file per layer that "
    "the builder should study to understand the project's patterns. Pick files from "
    "a completed feature that best represent the patterns the new milestone should "
    "follow. List ONE file per layer (entity, repository, service, controller, page), "
    "plus any shared infrastructure files the builder must modify (e.g. Program.cs "
    "for DI, AppDbContext.cs for DbSet, App.tsx for routing). For the first feature "
    "milestone, list only infrastructure files.\n\n"
    "When expanding a story into a milestone, READ THE CODEBASE FIRST: match existing "
    "patterns — if a BaseRepository<T> exists, use it; if DTOs are records, make new DTOs "
    "records. The new milestone should feel like a natural extension of what's already "
    "built.\n\n"
    "DETAIL IN TASK DESCRIPTIONS: Put implementation detail in task descriptions. "
    "Instead of 'Create Member entity' write 'Create Member entity (Id, FirstName, "
    "LastName, Email, Role enum, IsActive, OrganizationId)'. The builder should not "
    "need to cross-reference SPEC.md or REQUIREMENTS.md to understand what to create. "
    "Include field names, types, enum values, relationships, endpoint paths, and "
    "parameter names in the task text.\n\n"
    "TASK SIZING RULES:\n"
    "- Each task describes ONE logical change — one concept, one concern, one commit.\n"
    "- If a task description contains 'and', 'with', or a comma connecting distinct "
    "pieces of work, it is TOO BIG — split it.\n"
    "- If a task involves creating more than 3 endpoints, 3 entity definitions, or 3 "
    "pages, it is too big — split it.\n"
    "- Creating something new and integrating it elsewhere are ALWAYS separate tasks.\n"
    "- Configuring a tool and using that tool are separate tasks.\n"
    "- BAD: 'Create solution with 4 projects, configure references, and enable nullable'\n"
    "  GOOD: 'Create solution and Domain project' then 'Add Application and "
    "Infrastructure projects' then 'Add Api project and configure references'\n"
    "- BAD: 'Scaffold React + Vite frontend with Router, ESLint, Prettier, and strict TS'\n"
    "  GOOD: 'Scaffold React + Vite frontend with a placeholder root route' then "
    "'Add ESLint and Prettier configuration'\n\n"
    "MILESTONE SIZING RULES:\n"
    "- A well-sized milestone typically has 3-7 tasks. Under 3 suggests tasks might be "
    "too coarse. Over 8 suggests a natural split point exists — look for it.\n"
    "- Do NOT pack multiple concerns into one task to keep the milestone small.\n"
    "- If a feature area needs more than 7 tasks, create sequential milestones "
    "(e.g. 'Members — backend' then 'Members — frontend').\n\n"
    "MILESTONE TASK FORMAT — CRITICAL:\n"
    "Each task in the milestone file MUST use markdown checkbox syntax:\n"
    "```\n"
    "- [ ] Task description with implementation details\n"
    "```\n"
    "The builder agent marks tasks complete by changing `[ ]` to `[x]` after each commit. "
    "The orchestrator tracks milestone progress by counting checkboxes. Tasks without "
    "`- [ ]` checkboxes will NOT be detected and the milestone will appear empty.\n"
    "Do NOT use numbered headings (### 1.), plain bullets (- Task), or any other format "
    "for tasks. ONLY `- [ ]` checkboxes.\n\n"
    "EXAMPLE of a well-sized milestone — 'Members feature':\n"
    "- [ ] Create Member entity (Id, FirstName, LastName, Email, Role enum, IsActive, "
    "OrganizationId)\n"
    "- [ ] Create MemberRepository implementing BaseRepository<Member>\n"
    "- [ ] Create MemberService with list, get-by-id, create, update, deactivate operations\n"
    "- [ ] Create MembersController with GET /members, GET /members/:id, POST, PUT, DELETE\n"
    "- [ ] Create Members list page with search and add-member form\n"
    "- [ ] Create Member detail page with edit form and deactivate button\n"
    "This is 6 tasks. Each is one file or a tightly coupled pair. The milestone "
    "delivers one complete feature. That is the right size.\n\n"
    "RUNNABLE AFTER EVERY MILESTONE: Each milestone must leave the application in a "
    "buildable, startable state. The app must respond to at least one request — a health "
    "check endpoint, a root route, a --help flag, or similar — so that a container-based "
    "validator can confirm it works. Order tasks so the entry point, server, or main "
    "function exists before features are added.\n\n"
    "CONTAINERIZATION: Do not create stories or tasks for Dockerfiles, docker-compose "
    "files, or deployment configuration. A separate validator agent handles that. "
    "Do NOT add these to BACKLOG.md or milestone files.\n\n"
    "TESTING: Do not create stories, milestones, or tasks for writing tests. A "
    "separate testing agent writes tests automatically after each milestone. Do NOT "
    "add test stories to BACKLOG.md or test tasks to milestone files — they will never "
    "be planned and create false-positive warnings. If `reviews/` contains [cleanup] "
    "items, fold them into the next feature milestone as an extra task — never "
    "create a standalone cleanup milestone.\n\n"
    "Commit any changes to BACKLOG.md with message '[planner] Update backlog', and "
    "the milestone file with message '[planner] Plan milestone: <name>'. Run git pull "
    "--rebase, and push. If no changes are needed, do nothing."
)

BACKLOG_QUALITY_PROMPT = (
    "You are a planning quality reviewer. Your ONLY job is to evaluate and fix the "
    "story quality in BACKLOG.md. You must NOT "
    "write any application code or modify any source files other than BACKLOG.md.\n\n"
    "STEP 1 — READ:\n"
    "Read BACKLOG.md, REQUIREMENTS.md, and SPEC.md.\n\n"
    "STEP 2 — EVALUATE each criterion below. For any failure, fix BACKLOG.md "
    "directly.\n\n"
    "CRITERION C1 — SCAFFOLDING FIRST:\n"
    "Story #1 must be project scaffolding — creating project structure, entry point, "
    "and a health/hello endpoint. If story #1 is a feature story (e.g. 'Members — "
    "Create member entity'), move it down and make story #1 a scaffolding story.\n\n"
    "CRITERION C2 — VERTICAL SLICE ORIENTATION:\n"
    "Stories should represent user-facing features delivered through multiple layers, "
    "not single layers across all features. If more than 2 stories are layer-only "
    "(e.g. 'All domain entities', 'All repositories', 'All controllers'), "
    "restructure them into feature-oriented stories.\n\n"
    "CRITERION C3 — DESCRIPTION SPECIFICITY:\n"
    "Each story description should mention at least one concrete artifact — an entity "
    "name with fields, an endpoint path, a page name, or a specific behavior. "
    "If 2+ stories have zero concrete artifacts (e.g. 'implement member "
    "functionality'), add detail from REQUIREMENTS.md.\n\n"
    "CRITERION C4 — FEATURE COVERAGE:\n"
    "Every ## section in REQUIREMENTS.md should map to at least one story. For any "
    "uncovered section, add a story.\n\n"
    "CRITERION C5 — STORY SIZING (OVER-SPLITTING AND UNDER-SPLITTING):\n"
    "Each story becomes one Copilot session. Stories must be sized to produce 4-7 "
    "tasks each. Check for BOTH problems:\n"
    "- OVER-SPLITTING: A single CRUD feature (one entity) should not be split into "
    "more than 2 stories. If the same entity appears in 3+ stories, consolidate. "
    "If two adjacent stories for the same feature would each produce fewer than 4 "
    "tasks, merge them into one story.\n"
    "- UNDER-SPLITTING: If a story would clearly produce 9+ tasks (many entities, "
    "many pages, multiple complex workflows), split it at a natural boundary.\n"
    "- THIN STORIES: If a story's scope is too narrow to justify a session (e.g. "
    "a single config change, one admin page with no backend work, a standalone CSS "
    "tweak), merge it into the nearest related story.\n\n"
    "STEP 3 — COMMIT:\n"
    "If you made any changes, commit BACKLOG.md with message '[planner] Backlog "
    "quality fixes'. "
    "Run git pull --rebase, and push.\n"
    "If everything passes with no changes needed, do nothing and exit."
)

BACKLOG_ORDERING_PROMPT = (
    "You are a planning-only orchestrator. Your ONLY job is to reorder stories in "
    "BACKLOG.md to maximize parallel builder throughput while preserving vertical "
    "feature slices. You must NOT write any application code or modify any source "
    "files other than BACKLOG.md.\n\n"
    "STEP 1 — READ:\n"
    "Read BACKLOG.md.\n\n"
    "STEP 2 — REORDER FOR PARALLELISM:\n"
    "Reorder stories so that at every point in the backlog, the maximum number of "
    "stories are eligible to be built concurrently. Multiple builders claim stories "
    "in parallel — a story is eligible when ALL its dependencies are completed.\n\n"
    "Ordering principles (in priority order):\n"
    "1. A story must never appear before any story it depends on.\n"
    "2. Stories on the CRITICAL PATH (longest dependency chain) should appear as "
    "early as possible — they gate the most downstream work.\n"
    "3. Stories that UNBLOCK the most other stories should appear before stories "
    "that unblock fewer.\n"
    "4. Keep vertical feature slices together — a backend story and its matching "
    "frontend story should be adjacent (e.g. 'Members — backend' immediately "
    "followed by 'Members — admin pages'), not separated into backend-only and "
    "frontend-only blocks.\n"
    "5. Story #1 (scaffolding) always stays first.\n\n"
    "STEP 3 — RENUMBER:\n"
    "After reordering, renumber ALL stories sequentially starting from 1. "
    "Update ALL <!-- depends: N, M --> annotations to use the NEW story numbers. "
    "Keep the [x], [~], or [ ] status of each story unchanged. "
    "Keep each story's description text unchanged.\n\n"
    "STEP 4 — COMMIT:\n"
    "If you reordered anything, commit BACKLOG.md with message '[planner] Reorder "
    "backlog stories'. Run git pull --rebase, and push.\n"
    "If stories are already in correct order, do nothing and exit."
)

PLANNER_SPLIT_PROMPT = (
    "You are a planning-only orchestrator. You must NOT write any code or modify "
    "any source files. Milestone file `{milestone_file}` has {task_count} tasks, "
    "which is too many. Split it into two milestone files in `milestones/` of at most "
    "8 tasks each. Keep the same tasks — just reorganize them under new milestone "
    "headings in separate files. Each new file should be a coherent batch of related "
    "work. Delete the original oversized file after splitting. "
    "Do NOT modify BACKLOG.md or any other milestone files. "
    "Do NOT change any source files. "
    "Commit with message '[planner] Split oversized milestone: {milestone_name}', "
    "run git pull --rebase, and push."
)
