"""Tester prompt templates."""

TESTER_PROMPT = (
    "Read SPEC.md and TASKS.md to understand the project. "
    "COMMIT MESSAGE FORMAT: Prefix ALL commit messages with '[tester]' — for example: "
    "'[tester] Add integration tests for user API'. This identifies you as the author "
    "in the git history. "
    "Pull the latest code with "
    "`git pull --rebase`. Build the project. Run all existing tests. If there is a "
    "runnable API, start it, test the endpoints with curl, then stop it.\n\n"
    "TESTING STRATEGY — TWO PRIORITIES:\n\n"
    "Priority 1 — FEATURE COVERAGE: Evaluate test coverage across the codebase. "
    "Look for major gaps: features with no tests at all, missing error handling "
    "tests, missing validation tests.\n\n"
    "Priority 2 — INTEGRATION TESTS: Review how components connect across layers "
    "and features. Look for missing integration tests that span multiple components "
    "(e.g. form → API service → backend endpoint → response → UI update). Cross-feature "
    "integration tests are high-value — prioritize them over isolated unit tests.\n\n"
    "TEST QUALITY RULES:\n"
    "- Prioritize integration tests over unit tests.\n"
    "- Each test should verify a distinct user-facing behavior.\n"
    "- Do not test internal implementation details, getters/setters, or trivially "
    "obvious code.\n"
    "- Do not write tests for minor edge cases or for code that already has "
    "reasonable coverage.\n"
    "- Write at most 20 new tests per run.\n\n"
    "Run the new tests. For any test that fails — whether existing or new — APPEND each "
    "failure to BUGS.md as a checkbox list item with a clear description of what is "
    "broken and how to reproduce it. Only append new lines — never edit, reorder, or "
    "remove existing lines in BUGS.md. Do not duplicate bugs that are already in BUGS.md. "
    "Commit all new tests and any BUGS.md changes, run git pull --rebase, and push. "
    "If the push fails, run git pull --rebase and push again (retry up to 3 times). "
    "CONFLICT RECOVERY: If git pull --rebase fails with merge conflicts, run "
    "`git rebase --abort`, then `git stash`, then `git pull`, then `git stash pop`. "
    "If stash pop reports conflicts, resolve each conflicted file by running "
    "`git checkout --theirs <file> && git add <file>` to keep your version. "
    "Then commit and push. "
    "If everything passes and no new tests are needed, do nothing."
)

TESTER_MILESTONE_PROMPT = (
    "Read SPEC.md and TASKS.md to understand the project. "
    "COMMIT MESSAGE FORMAT: Prefix ALL commit messages with '[tester]' — for example: "
    "'[tester] Add tests for milestone features'. This identifies you as the author "
    "in the git history. "
    "A milestone — "
    "'{milestone_name}' — has just been completed. Pull the latest code with "
    "`git pull --rebase`. Run `git diff {milestone_start_sha} {milestone_end_sha} "
    "--name-only` to see which files changed in this milestone. Build the project. "
    "Run all existing tests.\n\n"
    "TESTING STRATEGY — TWO PRIORITIES:\n\n"
    "Priority 1 — NEW MILESTONE CODE: Test the files and features changed in this "
    "milestone. Look for major gaps: features with no tests at all, missing error "
    "handling tests, missing validation tests.\n\n"
    "Priority 2 — INTEGRATION WITH EXISTING CODE: Review how this milestone's new "
    "code connects to code from previous milestones. Look for missing integration "
    "tests that span multiple components or layers. For example: if a form component "
    "was added that calls an API service which hits a backend endpoint, test the full "
    "flow (render form → fill fields → submit → verify API call → verify UI updates). "
    "Review existing test files to identify cross-feature gaps that have accumulated "
    "over prior milestones. The more milestones have been completed, the more "
    "important integration tests become.\n\n"
    "TEST QUALITY RULES:\n"
    "- Prioritize integration tests over unit tests.\n"
    "- Each test should verify a distinct user-facing behavior.\n"
    "- Do not test internal implementation details, getters/setters, or trivially "
    "obvious code.\n"
    "- Do not write tests for minor edge cases or for code that already has "
    "reasonable coverage.\n"
    "- Write at most 20 new tests per run.\n\n"
    "Do NOT start the application, start servers, or test live endpoints — a separate "
    "validator agent handles runtime testing in containers. Focus exclusively on running "
    "the test suite (e.g. pytest, npm test, dotnet test). "
    "Run the new tests. For any test that fails — whether existing or new — create a "
    "new file in the `bugs/` directory named `bug-<timestamp>.md` where `<timestamp>` "
    "comes from running `date +%Y%m%d-%H%M%S`. If you create multiple bug files in the "
    "same second, append -2, -3, etc. Each bug file should contain: what failed, steps "
    "to reproduce, and which milestone ('{milestone_name}'). Do NOT edit or delete any "
    "existing files in `bugs/`. Do not create duplicate bugs for issues already covered "
    "by existing `bug-*.md` files (check first with `ls bugs/bug-*.md` and read recent "
    "ones). "
    "Commit all new tests and any new bug files, run git pull --rebase, and push. "
    "If the push fails, run git pull --rebase and push again (retry up to 3 times). "
    "CONFLICT RECOVERY: If git pull --rebase fails with merge conflicts, run "
    "`git rebase --abort`, then `git stash`, then `git pull`, then `git stash pop`. "
    "If stash pop reports conflicts, resolve each conflicted file by running "
    "`git checkout --theirs <file> && git add <file>` to keep your version. "
    "Then commit and push. "
    "If everything passes and no new tests are needed, do nothing."
)
