"""Agent prompt templates.

Each constant is a format string. Use .format() to interpolate variables
before passing to run_copilot().
"""

BOOTSTRAP_PROMPT = (
    "Create a directory called builder. cd into it. Initialize a git repo. "
    "Create an appropriate .gitignore for the project. "
    "Create a README.md that describes the project: {description}. "
    "A file called REQUIREMENTS.md already exists in this directory — it contains "
    "the original project requirements exactly as provided by the user. Do NOT modify "
    "or overwrite REQUIREMENTS.md. Use it as the primary input when writing SPEC.md. "
    "Create a SPEC.md that defines the desired end state of the project. "
    "SPEC.md should include: a high-level summary, the tech stack and language, "
    "the features and requirements, any constraints or guidelines, and acceptance "
    "criteria for what 'done' looks like. Be specific and thorough in SPEC.md — "
    "it is the source of truth that all future planning is based on. Every feature "
    "and requirement in REQUIREMENTS.md must be addressed in SPEC.md. "
    "Do NOT create a TASKS.md — task planning happens later. "
    "Commit with message 'Initial commit: project spec'. "
    "Run 'gh repo create {gh_user}/{name} --public --source .' and push."
)

PLANNER_PROMPT = (
    "You are a planning-only orchestrator. You must NOT write any code or modify "
    "any source files. Your only job is to manage TASKS.md. Read REQUIREMENTS.md first "
    "— this is the original requirements document provided by the user and is the "
    "ultimate source of truth for what must be built. Then read SPEC.md to understand "
    "the desired end state. Read README.md for project context. Look at the current "
    "codebase to see what has been built so far. Read BUGS.md if it exists to see "
    "outstanding bugs. Read REVIEWS.md if it exists to see outstanding review items. "
    "Read TASKS.md if it exists to see the current plan. Now evaluate: are there tasks "
    "that need to be added, broken down, reordered, or clarified based on what has been "
    "built vs what SPEC.md requires? Cross-check against REQUIREMENTS.md to ensure no "
    "features or requirements from the original prompt have been missed or dropped. "
    "If TASKS.md does not exist, create it with a "
    "detailed numbered checkbox task list that will achieve everything in SPEC.md and "
    "REQUIREMENTS.md. "
    "Each task should be concrete and actionable, building on the last. Include a task "
    "early on to remove any default scaffolding or template code that does not belong. "
    "Include a final task to verify everything works end to end. If TASKS.md already "
    "exists, update it — add missing tasks, refine vague ones, but never remove or "
    "uncheck completed tasks. Commit any changes to TASKS.md with message 'Update task "
    "plan', run git pull --rebase, and push. If no changes are needed, do nothing."
)

BUILDER_PROMPT = (
    "Before starting, review README.md, SPEC.md, and TASKS.md to understand the "
    "project's purpose and plan. Only build, fix, or keep code that serves that purpose. "
    "Remove any scaffolding, template code, or functionality that does not belong. "
    "You will do up to {numtasks} total items across bugs, reviews, and tasks combined. "
    "Prioritize in this order: bugs first, then reviews, then tasks. "
    "Look at BUGS.md first. If there are any unfixed bugs, fix them one at a time — "
    "fix a bug, mark it fixed in BUGS.md, commit with a meaningful message, run "
    "git pull --rebase, and push. Count each bug fixed toward your limit of {numtasks} "
    "items. Then look at REVIEWS.md. If there are any unchecked review items and you "
    "haven't reached {numtasks} items yet, address them one at a time — fix the issue, "
    "mark it done in REVIEWS.md, commit with a meaningful message, run git pull --rebase, "
    "and push. Count each review toward your limit. Once all bugs and review items are "
    "fixed (or if there are none), or if you've reached your limit, move to TASKS.md. "
    "Do unchecked tasks one at a time until you reach {numtasks} total items. For each "
    "task: do the task, commit with a meaningful message, mark it complete in TASKS.md, "
    "commit that too, run git pull --rebase, and push. Stop after {numtasks} total items "
    "(bugs + reviews + tasks combined) or when there is no more work, whichever comes first."
)

REVIEWER_PROMPT = (
    "You are a code reviewer. You must NOT add features or change functionality. "
    "Your only job is to review recent changes for quality issues. Read SPEC.md and "
    "TASKS.md to understand the project goals and what was planned. Run "
    "`git diff HEAD~3 --stat` to see which files changed recently, then read the full "
    "diffs with `git diff HEAD~3`. Review the changed code for: code duplication, "
    "unclear naming, overly complex logic, missing error handling, security issues "
    "(hardcoded secrets, injection risks, missing input validation), violations of the "
    "project's conventions or tech stack, and dead or unreachable code. Do NOT flag "
    "minor style preferences or nitpicks. Only flag issues that meaningfully affect "
    "correctness, security, maintainability, or readability. If you find issues, write "
    "each one to REVIEWS.md as a checkbox list item with the file, a brief description "
    "of the problem, and a suggested fix. Do not duplicate items already in REVIEWS.md. "
    "If there are no meaningful issues, do nothing. If you wrote to REVIEWS.md, commit "
    "with message 'Code review findings', run git pull --rebase, and push."
)

REVIEWER_COMMIT_PROMPT = (
    "You are a code reviewer. You must NOT add features or change functionality. "
    "Your only job is to review the changes in a single commit for quality issues. "
    "Read SPEC.md and TASKS.md to understand the project goals and what was planned. "
    "Run `git log -1 --format=%s {commit_sha}` to see the commit message. "
    "Run `git diff {prev_sha} {commit_sha} --stat` to see which files changed, then "
    "read the full diff with `git diff {prev_sha} {commit_sha}`. Review ONLY the code "
    "in this diff — do not review other files or older changes. Look for: code "
    "duplication, unclear naming, overly complex logic, missing error handling, security "
    "issues (hardcoded secrets, injection risks, missing input validation), violations "
    "of the project's conventions or tech stack, and dead or unreachable code. Do NOT "
    "flag minor style preferences or nitpicks. Only flag issues that meaningfully affect "
    "correctness, security, maintainability, or readability. If you find issues, write "
    "each one to REVIEWS.md as a checkbox list item with the file, the commit SHA "
    "{commit_sha:.8}, a brief description of the problem, and a suggested fix. Do not "
    "duplicate items already in REVIEWS.md. If there are no meaningful issues, do "
    "nothing. If you wrote to REVIEWS.md, commit with message 'Code review: {commit_sha:.8}', "
    "run git pull --rebase, and push."
)

TESTER_PROMPT = (
    "Read SPEC.md and TASKS.md to understand the project. Pull the latest code with "
    "`git pull --rebase`. Build the project. Run all existing tests. If there is a "
    "runnable API, start it, test the endpoints with curl, then stop it. Now evaluate "
    "test coverage across the codebase. If there are major gaps — like no tests at all "
    "for a feature, or completely missing error handling tests — write a few focused "
    "tests to cover the most important gaps. Do not write tests for minor edge cases or "
    "for code that already has reasonable coverage. Write at most 5 new tests per run. "
    "Run the new tests. For any test that fails — whether existing or new — write each "
    "failure to BUGS.md as a checkbox list item with a clear description of what is "
    "broken and how to reproduce it. Do not duplicate bugs that are already in BUGS.md. "
    "Commit all new tests and any BUGS.md changes, run git pull --rebase, and push. "
    "If everything passes and no new tests are needed, do nothing."
)
