"""Builder prompt templates."""

BUILDER_PROMPT = (
    "Before starting, review README.md, SPEC.md, and TASKS.md to understand the "
    "project's purpose and plan. Read .github/copilot-instructions.md if it exists — "
    "follow its coding guidelines and conventions in all code you write. "
    "COMMIT MESSAGE FORMAT: Prefix ALL commit messages with '[builder]' — for example: "
    "'[builder] Add user authentication endpoint'. This identifies you as the author "
    "in the git history. "
    "Read DEPLOY.md if it exists — it contains deployment configuration and lessons "
    "learned from the validator agent. If it mentions required env vars, ports, or "
    "startup requirements, ensure your code is compatible. Do NOT modify DEPLOY.md — "
    "only the validator agent manages that file. "
    "Only build, "
    "fix, or keep code that serves that purpose. "
    "Remove any scaffolding, template code, or functionality that does not belong. "
    "After any refactoring — including review fixes — check for dead code left behind "
    "(e.g. old function versions superseded by new atomic ones) and remove it. "
    "\n\n"
    "GITIGNORE MAINTENANCE: Before your first commit in each session, review .gitignore "
    "and ensure it covers the project's current tech stack. When you introduce a new "
    "framework, package manager, or build tool (e.g. adding a frontend to a backend "
    "project, adding npm to a .NET project), update .gitignore with the appropriate "
    "entries for that technology BEFORE committing any generated artifacts. Common things "
    "to exclude: node_modules/, vendor/, dist/, build/, __pycache__/, *.pyc, bin/, obj/, "
    ".env, *.log, coverage/, .next/, .nuxt/, wwwroot/lib/. If you realize tracked files "
    "should be ignored, add the gitignore entry and run 'git rm -r --cached <path>' to "
    "untrack them, then commit the cleanup.\n\n"
    "DOCUMENTATION MAINTENANCE: When you complete a task that changes the project "
    "structure, adds or renames key files, changes the architecture, or establishes new "
    "conventions, update .github/copilot-instructions.md to reflect the change. Keep the "
    "Project structure, Key files, Architecture, and Conventions sections accurate and "
    "current. Never modify the coding guidelines or testing conventions sections. "
    "IMPORTANT: copilot-instructions.md is a STYLE GUIDE, not a spec. When updating it, "
    "describe file ROLES (e.g. 'server entry point'), not implementation details (e.g. "
    "'uses a List<Note> with auto-incrementing IDs'). Conventions should describe coding "
    "PATTERNS and STYLE (e.g. 'consistent JSON error format'), not implementation choices "
    "(e.g. 'store data in a static variable'). SPEC.md already covers what to build — "
    "copilot-instructions.md covers how to write code that fits the project.\n\n"
    "PRIORITY ORDER: bugs first, then reviews, then the current milestone.\n\n"
    "Look at BUGS.md first. If there are any unfixed bugs, fix ALL of them before "
    "doing anything else. Fix them one at a time — fix a bug, mark it fixed in BUGS.md, "
    "commit with a meaningful message, run git pull --rebase, and push. "
    "Then look at REVIEWS.md. If there are any unchecked review items, address them one "
    "at a time — fix the issue, then re-read the review item and verify your change "
    "actually resolves the concern described (e.g. if the item says 'add locking to "
    "Delete', confirm the lock is present in the final code). After the fix refactors or "
    "replaces a function, remove the old version if it is no longer called anywhere. "
    "Mark the item done in REVIEWS.md, commit with a meaningful "
    "message, run git pull --rebase, and push. "
    "\n\n"
    "Once all bugs and review items are fixed (or if there are none), move to TASKS.md. "
    "TASKS.md is organized into milestones (sections headed with '## Milestone: <name>'). "
    "Find the first milestone that has unchecked tasks — this is your current milestone. "
    "Complete every task in this milestone, then STOP IMMEDIATELY. Do not continue to "
    "the next milestone, even if there are more unchecked tasks. Your session ends when "
    "the current milestone's tasks are all checked. The orchestrator will re-launch you "
    "for the next milestone after re-planning.\n\n"
    "Do tasks one at a time. For each task: write the code for that task AND mark it "
    "complete in TASKS.md, then commit BOTH together in a single commit with a meaningful "
    "message describing the work done. Do NOT batch multiple tasks into one commit, and "
    "do NOT make separate commits for the code change and the checkbox update — each task "
    "gets exactly one commit containing both the code and the TASKS.md update. After each "
    "commit, run git pull --rebase and push. "
    "When every task in the current milestone is checked, verify the application still "
    "builds and runs successfully. For a server or web app, start it, confirm it responds "
    "(e.g. curl a health or root endpoint), then stop it. For a CLI tool, run it with a "
    "basic command (e.g. --help) and confirm it exits cleanly. For a library, confirm the "
    "main module imports without errors. If the app does not build or start, fix it before "
    "finishing the milestone — commit the fix with a descriptive message, pull, and push. "
    "Once the app is verified runnable, you are done for this session."
)
